CREATE DATABASE MANAGER_HOSPITAL;
USE MANAGER_HOSPITAL;
-- TẠO BẢNG
CREATE TABLE PATIENTS (
    PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FULL_NAME VARCHAR(100),
    PHONE VARCHAR(15),
    AGE INT,
    ADDRESS VARCHAR(255)
);
-- PROCEDURE CHÈN 500.000 DÒNG
DELIMITER //
CREATE PROCEDURE SEEDPATIENTS()
BEGIN
    DECLARE I INT DEFAULT 1;
    WHILE I <= 500000 DO
        INSERT INTO PATIENTS (FULL_NAME, PHONE, AGE, ADDRESS)
        VALUES (CONCAT('PATIENT ', I), CONCAT('090', LPAD(I,7,'0')), FLOOR(RAND()*100), 'HO CHI MINH CITY');
        SET I = I + 1;
    END WHILE;
END //
DELIMITER ;

CALL SEEDPATIENTS();
-- KIỂM TRA TỐC ĐỘ TRUY VẤN CHƯA INDEX
EXPLAIN ANALYZE
SELECT * FROM PATIENTS
WHERE PHONE = '0900000002';
-- TRUY VẤN
SELECT * FROM PATIENTS
WHERE PHONE = '0900000002';
-- TẠO INDEX
CREATE INDEX IDX_PHONE 
ON PATIENTS(PHONE);
-- KIỂM TRA TỐC ĐỘ TRUY VẤN CÓ INDEX
EXPLAIN ANALYZE
SELECT * FROM PATIENTS
WHERE PHONE = '0900000002';
-- TRUY VẤN
SELECT * FROM PATIENTS
WHERE PHONE = '0900000002';
-- KIỂM TRA TỐC ĐỘ CHÈN DỮ LIỆU KHI CÓ INDEX
INSERT INTO PATIENTS (FULL_NAME, PHONE, AGE, ADDRESS)
VALUES ('NGUYEN VAN A', '0987654321', 50, 'HN');
-- XÓA 
DROP INDEX IDX_PHONE ON PATIENTS;
-- KIỂM TRA TỐC ĐỘ CHÈN DỮ LIỆU KHI KHÔNG INDEX
INSERT INTO PATIENTS (FULL_NAME, PHONE, AGE, ADDRESS)
VALUES ('TRAN LAN B', '0123456789', 25, 'HN');

/*
NHẬN XÉT:
	VIỆC TẠO INDEX GIÚP CẢI THIỆN TỐC ĐỘ TRUY VẤN DỮ LIỆU ĐỔI LẠI TỐC ĐỘ GHI DỮ LIỆU BỊ GIẢM HIỆU NĂNG DO PHẢI CẬP NHẬT CẢ CẤU TRÚC CHỈ MỤC
*/
